// Webpack asset/resource
declare module '*.ico'
declare module '*.gif'
declare module '*.png'
declare module '*.jpg'
declare module '*.jpeg'
// Webpack asset/inline
declare module '*.woff'
declare module '*.eot'
declare module '*.ttf'
declare module '*.otf'
declare module '*.svg'